<?xml version='1.0' encoding='utf-8'?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>morpheus_driver</name>
  <version>2.0.0</version>
  <description>The morpheus_driver package</description>
  <maintainer email="bshuo@ucdavis.edu">Brian Sanyu Huo</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>control_msgs</depend>
  <depend>ur_robot_driver</depend>
  <depend>robotiq_driver</depend>
  <depend>onrobot_driver</depend>
<!--
  <depend>cartesian_controller</depend>
  <depend>cartesian_controller_simulation</depend>
-->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
