# References:
# GPU Passthrough in WSL: https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md
# Realtime task priority: https://control.ros.org/rolling/doc/ros2_control/controller_manager/doc/userdoc.html
services:
  morpheus2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morpheus2
    command: tail -F /dev/null # Entrypoint. /dev/null discards print

    # Enable realtime task priority
    privileged: true
    network_mode: host
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      memlock: -1

    environment:
      # Share GUI environment variables with the container.
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      # Fix a bug with QT
      - QT_X11_NO_MITSHM=1
      # Grant display access to X Server.
      - XAUTHORITY
       # Configure for Moveit and Gazebo
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - RCUTILS_COLORIZED_OUTPUT=1
      - GZ_VERSION=harmonic
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_DISABLE_REQUIRE=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - LIBVA_DRIVER_NAME=d3d12
    volumes:
      # Share X11, Wayland, and/or Pulse servers with the container.
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      # Share the Xauthority file with the container.
      - ${XAUTHORITY}:${XAUTHORITY}
      # Mount the ROS workspace into the container.
      - .:/root/ros2_ws/src
      # Share input devices and GPU with the container.
      - /dev:/dev
      # Share WSL mount locations with the container
      - /usr/lib/wsl:/usr/lib/wsl

    # Reserve GPU resource
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]