session_state_dict = {
    "intro":["id"],
    "id":["task"],
    "task":["trial"],
    "trial":["ready"],
    "ready":["recording"],
    "recording":[],
}

session_string_dict = {
    "header_title":"Morpheus Recording Session",
    "header_id":"Subject ID: ",
    "header_task":"Task Name: ",
    "header_trial":"Trial Number: ",
    "intro_description":"Press ENTER to continue, or press ESC to cancel.",
    "id_description":"Please enter subject ID: ",
    "id_enter":"Subject ID is ",
    "id_esc":"Ending recording session.",
    "task_description":"Please enter task name: ",
    "task_enter":"Task is ",
    "task_esc":"Cancelling task selection.",
    "trial_description":"Please enter trial number (or leave blank to use next available index): ",
    "trial_enter":"Trial number is ",
    "trial_esc":"Cancelling task selection.",
    "ready_description":"Ready to record. Press ENTER to start or ESC to go back.",
    "ready_enter":"Starting recording ",
    "ready_esc":"Exiting recording ",
    "recording_description":"Now recording. Press ENTER or ESC to stop.",
    "recording_enter":"Stopping recording ",
    "recording_esc":"Stopping recording ",
    "recording_taken":"Filename already exists! Press ESC to re-enter trial number and try again.",
}