<?xml version='1.0' encoding='utf-8'?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>morpheus_main</name>
  <version>2.0.0</version>
  <description>The morpheus_main package</description>
  <maintainer email="bshuo@ucdavis.edu">Brian Sanyu Huo</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>ur_robot_driver</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
