controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    finger_width_controller:
      type: position_controllers/JointGroupPositionController
  
    onrobot_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

finger_width_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)finger_width

onrobot_gripper_controller:
  ros__parameters:
    joint: $(var tf_prefix)finger_width

    # Enable effort control (replacement for use_effort_interface)
    # max_effort_interface: "$(var tf_prefix)finger_width/effort"
    # max_effort: 50.0   # TODO tune

    # Enable velocity/speed control (replacement for use_speed_interface)
    # max_velocity_interface: "$(var tf_prefix)finger_width/velocity"
    # max_velocity: 0.5    # TODO tune

    # Optional (recommended)
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02
