<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>morpheus_hera</name>
  <version>1.0.0</version>
  <description>The morpheus_hera package</description>
  <maintainer email="bshuo@ucdavis.edu">Brian Sanyu Huo</maintainer>
  <license>GPLv3</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>joy</build_depend>
  <build_depend>rclpy</build_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>joy</build_export_depend>
  <build_export_depend>rclpy</build_export_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
