<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>morpheus_gui</name>
  <version>1.0.0</version>
  <description>The morpheus_gui package</description>
  <maintainer email="bshuo@ucdavis.edu">Brian Sanyu Huo</maintainer>
  <license>GPLv3</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
