<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>morpheus_collision</name>
  <version>1.0.0</version>
  <description>The morpheus_collision package</description>
  <maintainer email="bshuo@ucdavis.edu">Brian Sanyu Huo</maintainer>
  <license>GPLv3</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>joy</depend>
  <depend>rclpy</depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_core</depend>
  <depend>moveit_ros_planning</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_visual_tools</depend>
  <depend>moveit_msgs</depend>
  <depend>morpheus_msgs</depend>
  <depend>geometric_shapes</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
