collision_object_presets:
  dragon:
    mesh_path: "/meshes/components/collision/dragon_simple.obj"
    scale: [0.0254, 0.0254, 0.0254]
    position: [0.6, 0.2, 1.2]
    quaternion: [0.0, 0.0, 0.0, 1.0]
  teapot:
    mesh_path: "/meshes/components/collision/teapot.obj"
    scale: [0.0254, 0.0254, 0.0254]
    position: [-0.1, 0.8528, 0.91915]
    quaternion: [0.0, 0.0, 0.0, 1.0]
  bar_12in:
    mesh_path: "/meshes/components/collision/bar_12in.obj"
    scale: [0.0254, 0.0254, 0.0254]
    position: [-0.1, 0.8528, 0.91915]
    quaternion: [0.0, 0.0, 0.0, 1.0]